[package]
name = "rmsafe"
version = "2.3.0"
edition = "2021"
description = "safely removing files and directories; moving them to trash"
license = "MIT"
authors = ["Adhyan H. <adhyanpatel@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
love_rust = "0.3.0"
clap = { version = "4.0.26", features = ["derive"] }
glob = "0.3.0"
rand = "0.8.5"
confy = "0.5.1"
chrono = "0.4.23"
serde = "1.0.147"
serde_derive = "1.0.147"

[profile.release]
strip = true
opt-level = "z"
lto = true
