[package]
name = "saferm"
version = "1.3.0"
edition = "2021"
about = "safely removing files and directories; moving them to trash"
authors = ["Adhyan H. <adhyanpatel@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
glob = "0.3.0"