[package]
name = "rmsafe"
version = "2.1.3"
edition = "2021"
about = "safely removing files and directories; moving them to trash"
description = "after almost accidentally rm(ing) my C homework folder, I decided to create this to NOT do that in the future, goal is to do everything that the unix command rm can do"
license = "MIT"
authors = ["Adhyan H. <adhyanpatel@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
love_rust = "0.2.2"
clap = { version = "4.0.26", features = ["derive"] }
glob = "0.3.0"
rand = "0.8.5"
confy = "0.5.1"
serde = "1.0.147"
serde_derive = "1.0.147"

[profile.release]
strip = true
opt-level = "z"
lto = true
